### ISSUE TITLE
No reaction starting a new project

### ISSUE THREAD

**Issue by incoggnito** [koxudaxi/poetry-pycharm-plugin#178]
**Describe the bug**
Start pycharm click to add a new project nothing happens.
Same is behaviour in Linux and Windows.
Poetry is currently the only plugin.

**Screenshots**
![image](https://user-images.githubusercontent.com/44142874/107283807-2cbcb700-6a5d-11eb-8167-2078a7862aaa.png)

**Environments (please complete the following information):**
 - IDE: PyCharm Community 2020.3.3-1
 - OS: ArchLinux or Windows 10
 - Poetry Version 1.1.4
 - Plugin version 1.0.5

**Comment by koxudaxi** [comment]
@incoggnito 
Thank you for creating this issue.
I just checked your log.
But, I can't found poetry error without the last line.
I guess stack trace should show us the factor of error like https://github.com/koxudaxi/poetry-pycharm-plugin/issues/175.
Did you get the same error when you uninstall the poetry plugin?

**Comment by incoggnito** [comment]
Thank you for fast response.

Here using grep "poetry" on the stdout.
```
	at com.koxudaxi.poetry.PoetryKt.tomlTableHeaderHasKey(poetry.kt:721)
	at com.koxudaxi.poetry.PoetryKt.<clinit>(poetry.kt:722)
	at com.koxudaxi.poetry.PyAddNewPoetryPanel.<init>(PyAddNewPoetryPanel.kt:56)
	at com.koxudaxi.poetry.PoetrySdkProvider.createNewEnvironmentPanel(PoetrySdkProvider.kt:56)
Caused by: java.lang.ClassNotFoundException: org.toml.lang.psi.TomlTableHeader PluginClassLoader[PluginDescriptor(name=Poetry, id=com.koxudaxi.poetry, path=/home/inco/.local/share/JetBrains/PyCharmCE2020.3/poetry-pycharm-plugin, version=1.0.5)] com.intellij.ide.plugins.cl.PluginClassLoader@2c7eb65c
2021-02-09 08:12:21,068 [   5558]  ERROR - pplication.impl.LaterInvocator - Could not initialize class com.koxudaxi.poetry.PoetryKt
java.lang.NoClassDefFoundError: Could not initialize class com.koxudaxi.poetry.PoetryKt
	at com.koxudaxi.poetry.PoetrySdkProvider.getSdkAdditionalText(PoetrySdkProvider.kt:59)
2021-02-09 08:12:21,070 [   5560]  ERROR - pplication.impl.LaterInvocator - Could not initialize class com.koxudaxi.poetry.PoetryKt
java.lang.NoClassDefFoundError: Could not initialize class com.koxudaxi.poetry.PoetryKt
	at com.koxudaxi.poetry.PoetrySdkProvider.getSdkAdditionalText(PoetrySdkProvider.kt:59)
```

I already have a systemwide version of poetry installed on both systems. How does the plugin use poetry?

**Comment by koxudaxi** [comment]
I confirmed your error.
The error is the same error in https://github.com/koxudaxi/poetry-pycharm-plugin/issues/175
I have closed this issue as a duplicated issue.

Thank you very much!!
